import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Suspense } from 'react'
import LoadingComponent from "./components/LoadingComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hiraise Realestate",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<LoadingComponent />}>
          <Navbar />
          {children}
        </Suspense>

      </body>
    </html>
  );
}
